export type ScrapbookEntry = {
  id: string;
  src: string;
  alt: string;
  caption: string;
  collection: string;
  category: "Events" | "Drinks";
  date: string;
};
export const entries: ScrapbookEntry[] = [
  {
    id: "apron-pour-fall-2026",
    caption: "Fall 2026",
    collection: "",
    category: "Drinks",
    date: "Fall 2026",
    alt: "A person wearing a Latte Lab apron pouring coffee into a glass",
  },
  {
    id: "passionfruit-coldbrew-fall-2026",
    caption: "Passionfruit lemonade cold brew",
    collection: "First semester event: Brew and Meet!",
    category: "Drinks",
    date: "Fall 2026",
    alt: "A hand holding passionfruit lemonade cold brew in a clear Latte Lab cup, backlit against orange and turquoise",
  },
  {
    id: "csail-rd-event",
    caption: "Brewing at the CSAIL R&D event",
    collection: "Latte Lab x CSAIL",
    category: "Events",
    date: "Spring 2026",
    alt: "A Latte Lab member in a Latte Lab apron talking with a teammate behind the counter at the CSAIL R&D event, with a coffee maker and espresso machine on the counter",
  },
  {
    id: "korean-momma-pourover",
    caption: "A pourover lesson with Korean Momma",
    collection: "Korean Momma collaboration",
    category: "Events",
    date: "Spring 2026",
    alt: "Latte Lab members seated around a table for a Korean Momma x Latte Lab pourover event, with a presenter explaining brewing in front of a whiteboard",
  },
  {
    id: "matching-sweaters",
    caption: "Matching sweaters, good company",
    collection: "Latte Lab moments",
    category: "Events",
    date: "Spring 2026",
    alt: "Latte Lab members posing together in matching brown Latte Lab sweatshirts",
  },
  {
    id: "dubai-coffee-taste-test",
    caption: "Dubai coffee taste test",
    collection: "Dubai coffee taste test",
    category: "Drinks",
    date: "Spring 2026",
    alt: "A latte with leaf-pattern latte art next to a Soil Roasters coffee bag and three chocolate-dusted treats on a wooden tray",
  },
  {
    id: "photoshoot-polaroids",
    caption: "Latte Lab photoshoot shots",
    collection: "Latte Lab photoshoot",
    category: "Events",
    date: "Spring 2026",
    alt: "Three instant photos of Latte Lab members arranged on a wooden table beside a lamp and an amber glass",
  },
  {
    id: "figma-spring-2026",
    caption: "A matcha for Latte Lab x Figma",
    collection: "Latte Lab x Figma",
    category: "Drinks",
    date: "Spring 2026",
    alt: "An iced matcha latte with a Latte Lab member sticker on the cup, layered over a brown sauce at the bottom",
  },
  {
    id: "halloween-ghost-2025",
    caption: "A little ghost, a lot of coffee",
    collection: "Halloween 2025",
    category: "Drinks",
    date: "Fall 2025",
    alt: "A person in a white ghost costume holding an iced coffee with a hand-drawn ghost face on the cup",
  },
  {
    id: "salted-caramel-butter-pecan",
    caption: "Salted caramel cold foam butter pecan latte",
    collection: "Seasonal drink menu",
    category: "Drinks",
    date: "Fall 2025",
    alt: "An iced salted caramel cold foam butter pecan latte in a glass, surrounded by pumpkins and gourds",
  },
  {
    id: "halloween-2025",
    caption: "A little spooky, a lot of company",
    collection: "Halloween 2025",
    category: "Events",
    date: "Fall 2025",
    alt: "Seven friends posing together in costumes at Latte Lab’s Halloween 2025 event",
  },
  {
    id: "halloween-filming-2025",
    caption: "Halloween content filming",
    collection: "Halloween 2025",
    category: "Events",
    date: "Fall 2025",
    alt: "A person dressed as a ghost with sunglasses and a small pumpkin on their head, holding a ghost-decorated drink",
  },
  {
    id: "blueprint-6",
    caption: "Behind the coffee counter",
    collection: "Hack Blueprint",
    category: "Events",
    date: "Spring 2026",
    alt: "Latte Lab volunteers in aprons serving coffee at Blueprint",
  },
  {
    id: "saas-1",
    caption: "A little something floral",
    collection: "SAAS collaboration",
    category: "Drinks",
    date: "Fall 2025",
    alt: "Latte art in a white cup decorated with rose petals",
  },
  {
    id: "social-2",
    caption: "The best part is the company",
    collection: "Social & recipe testing",
    category: "Events",
    date: "Fall 2025",
    alt: "Members chatting around a table during a Latte Lab social",
  },
  {
    id: "blueprint-4",
    caption: "Coffee break, campus edition",
    collection: "Hack Blueprint",
    category: "Events",
    date: "Spring 2026",
    alt: "The Latte Lab pop-up counter with students serving coffee",
  },
  {
    id: "social-3",
    caption: "Made to be shared",
    collection: "Social & recipe testing",
    category: "Events",
    date: "Fall 2025",
    alt: "Preparing and sharing food around a table at a club social",
  },
  {
    id: "saas-2",
    caption: "A moment between sips",
    collection: "SAAS collaboration",
    category: "Events",
    date: "Fall 2025",
    alt: "A club participant seated at the café table",
  },
  {
    id: "blueprint-7",
    caption: "A good day for good coffee",
    collection: "Hack Blueprint",
    category: "Events",
    date: "Spring 2026",
    alt: "Volunteers preparing drinks behind the Blueprint counter",
  },
  {
    id: "social-1",
    caption: "Pull up another chair",
    collection: "Social & recipe testing",
    category: "Events",
    date: "Fall 2025",
    alt: "Friends gathered around a long table for a club social",
  },
  {
    id: "social-6",
    caption: "Recipes, stories, seconds",
    collection: "Social & recipe testing",
    category: "Events",
    date: "Fall 2025",
    alt: "Members exchanging food and conversation during recipe testing",
  },
  {
    id: "saas-3",
    caption: "See you at the next one",
    collection: "SAAS collaboration",
    category: "Events",
    date: "Fall 2025",
    alt: "Students hanging out at a café table",
  },
].map((entry) => ({
  ...entry,
  category: entry.category as "Events" | "Drinks",
  src: `/photos/${entry.id}.webp`,
}));
