export type ScrapbookEntry = {
  id: string;
  src: string;
  alt: string;
  caption: string;
  collection: string;
  category: "Events" | "Drinks";
  date: string;
};
export const entries: ScrapbookEntry[] = [
  {
    id: "matching-sweaters",
    caption: "Matching sweaters, good company",
    collection: "Latte Lab moments",
    category: "Events",
    date: "",
    alt: "Latte Lab members posing together in matching brown Latte Lab sweatshirts",
  },
  {
    id: "passionfruit-coldbrew-fall-2026",
    caption: "Passionfruit lemonade cold brew",
    collection: "First event of fall 2026",
    category: "Drinks",
    date: "Fall 2026",
    alt: "A hand holding passionfruit lemonade cold brew in a clear Latte Lab cup, backlit against orange and turquoise",
  },
  {
    id: "photoshoot-polaroids",
    caption: "Latte Lab photoshoot shots",
    collection: "Latte Lab photoshoot",
    category: "Events",
    date: "",
    alt: "Three instant photos of Latte Lab members arranged on a wooden table beside a lamp and an amber glass",
  },
  {
    id: "halloween-2025",
    caption: "A little spooky, a lot of company",
    collection: "Halloween 2025",
    category: "Events",
    date: "October 2025",
    alt: "Seven friends posing together in costumes at Latte Lab’s Halloween 2025 event",
  },
  {
    id: "halloween-filming-2025",
    caption: "Halloween content filming",
    collection: "Halloween 2025",
    category: "Events",
    date: "October 2025",
    alt: "A person dressed as a ghost with sunglasses and a small pumpkin on their head, holding a ghost-decorated drink",
  },
  {
    id: "blueprint-6",
    caption: "Behind the coffee counter",
    collection: "Hack Blueprint",
    category: "Events",
    date: "February 2026",
    alt: "Latte Lab volunteers in aprons serving coffee at Blueprint",
  },
  {
    id: "saas-1",
    caption: "A little something floral",
    collection: "SAAS collaboration",
    category: "Drinks",
    date: "October 2025",
    alt: "Latte art in a white cup decorated with rose petals",
  },
  {
    id: "social-2",
    caption: "The best part is the company",
    collection: "Social & recipe testing",
    category: "Events",
    date: "October 2025",
    alt: "Members chatting around a table during a Latte Lab social",
  },
  {
    id: "blueprint-1",
    caption: "A cup to keep you going",
    collection: "Hack Blueprint",
    category: "Drinks",
    date: "February 2026",
    alt: "A hand holding a finished drink in front of the Blueprint chalkboard",
  },
  {
    id: "blueprint-4",
    caption: "Coffee break, campus edition",
    collection: "Hack Blueprint",
    category: "Events",
    date: "February 2026",
    alt: "The Latte Lab pop-up counter with students serving coffee",
  },
  {
    id: "social-3",
    caption: "Made to be shared",
    collection: "Social & recipe testing",
    category: "Events",
    date: "October 2025",
    alt: "Preparing and sharing food around a table at a club social",
  },
  {
    id: "saas-5",
    caption: "One more look at that pour",
    collection: "SAAS collaboration",
    category: "Drinks",
    date: "October 2025",
    alt: "Overhead view of a latte with petals beside the cup",
  },
  {
    id: "saas-2",
    caption: "A moment between sips",
    collection: "SAAS collaboration",
    category: "Events",
    date: "October 2025",
    alt: "A club participant seated at the café table",
  },
  {
    id: "blueprint-7",
    caption: "A good day for good coffee",
    collection: "Hack Blueprint",
    category: "Events",
    date: "February 2026",
    alt: "Volunteers preparing drinks behind the Blueprint counter",
  },
  {
    id: "social-1",
    caption: "Pull up another chair",
    collection: "Social & recipe testing",
    category: "Events",
    date: "October 2025",
    alt: "Friends gathered around a long table for a club social",
  },
  {
    id: "social-6",
    caption: "Recipes, stories, seconds",
    collection: "Social & recipe testing",
    category: "Events",
    date: "October 2025",
    alt: "Members exchanging food and conversation during recipe testing",
  },
  {
    id: "saas-3",
    caption: "See you at the next one",
    collection: "SAAS collaboration",
    category: "Events",
    date: "October 2025",
    alt: "Students hanging out at a café table",
  },
].map((entry) => ({
  ...entry,
  category: entry.category as "Events" | "Drinks",
  src: `/photos/${entry.id}.webp`,
}));
